-- Den globala övningskatalogen seedas numera av migrationen
-- 20260825090000_seed_global_exercises.sql, inte härifrån - `supabase db
-- push` kör aldrig den här filen, bara `supabase db reset` (lokal
-- utveckling), så katalogen nådde aldrig ett riktigt projekt.
